name: Bahmni Form Controls Package

on:
  push:
    branches:
      - master
      - "release-*"
    tags:
      - "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Node JS v18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"
      - run: npm cache clean --force
      - name: Install dependencies
        run: brew install automake autoconf libtool dpkg pkgconfig nasm libpng
      - name: npm install
        run: npm install --legacy-peer-deps
      - name: npm test
        run: npm test
      - run: npm ci
      # - name: Publish the package
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: yarn publish

      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      #     always-auth: true
